# Generated synthetic NER training data for FRA forms
TRAIN_DATA = [
    ('Name of the claimant(s): Arvind Yadav\nVillage: Rampur\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 53, 'VILLAGE'), (75, 103, 'EVIDENCE')]}),
    ('Name of the spouse: Sunita\nTehsil/Taluka: Bilaspur\nScheduled Tribe: No', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 50, 'TEHSIL'), (68, 70, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Pankaj Kumar\nTehsil/Taluka: Katni\nLand for in situ rehabilitation: Under process', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 58, 'TEHSIL'), (92, 105, 'REHAB_LAND')]}),
    ('Name of spouse: Mohan Lal\nDistrict: Raipur\nPattas/leases/grants, if any: Not applicable', {'entities': [(16, 25, 'SPOUSE_NAME'), (36, 42, 'DISTRICT'), (73, 87, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Kurnool\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 46, 'DISTRICT'), (77, 89, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Jagdalpur\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (80, 87, 'DISPUTED_LANDS')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Rajpur\nExtent of forest land occupied: 2 hectares', {'entities': [(23, 33, 'PARENT_NAME'), (50, 56, 'GRAM_PANCHAYAT'), (89, 99, 'FOREST_LAND_EXTENT')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Kundapur\nExtent of forest land occupied: 2 hectares', {'entities': [(23, 35, 'PARENT_NAME'), (52, 60, 'GRAM_PANCHAYAT'), (93, 103, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Tara Singh\nTehsil/Taluka: Sihora\nLand for in situ rehabilitation: Required', {'entities': [(25, 35, 'CLAIMANT_NAME'), (51, 57, 'TEHSIL'), (91, 99, 'REHAB_LAND')]}),
    ('Name of spouse: Sunita\nDistrict: Raipur\nPattas/leases/grants, if any: Pending', {'entities': [(16, 22, 'SPOUSE_NAME'), (33, 39, 'DISTRICT'), (70, 77, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Badwara\nDisputed lands if any: None', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 51, 'VILLAGE'), (75, 79, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Jagdalpur\nDisputed lands if any: Entire area', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (80, 91, 'DISPUTED_LANDS')]}),
    ('Name of father/mother: Kamla Devi\nAny other traditional right: Fishing rights', {'entities': [(23, 33, 'PARENT_NAME'), (63, 77, 'OTHER_RIGHT')]}),
    ('Name of father/mother: Kamla Devi\nAny other traditional right: Fishing rights', {'entities': [(23, 33, 'PARENT_NAME'), (63, 77, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Ramesh Kumar\nVillage: Katni\nDistrict: Raipur\nScheduled Tribe: Yes', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (63, 69, 'DISTRICT'), (87, 90, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Rajpur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 35, 'PARENT_NAME'), (52, 58, 'GRAM_PANCHAYAT'), (91, 102, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Ramesh Kumar\nVillage: Jagdalpur\nDisputed lands if any: Entire area', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (80, 91, 'DISPUTED_LANDS')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Raipur\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 45, 'DISTRICT'), (76, 88, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of father/mother: Suresh Singh\nAny other traditional right: Grazing', {'entities': [(23, 35, 'PARENT_NAME'), (65, 72, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Rampur\nDisputed lands if any: None', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 53, 'VILLAGE'), (77, 81, 'DISPUTED_LANDS')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Sihora\nPattas/leases/grants, if any: Pending', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 45, 'DISTRICT'), (76, 83, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Katni\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (74, 102, 'EVIDENCE')]}),
    ('Name of father/mother: Suresh Singh\nGram Panchayat: Rampur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 35, 'PARENT_NAME'), (52, 58, 'GRAM_PANCHAYAT'), (91, 98, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Badwara\nDisputed lands if any: Entire area', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 52, 'VILLAGE'), (76, 87, 'DISPUTED_LANDS')]}),
    ('Name of the spouse: Radha Kumari\nTehsil/Taluka: Sihora\nScheduled Tribe: No', {'entities': [(20, 32, 'SPOUSE_NAME'), (48, 54, 'TEHSIL'), (72, 74, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Lakshmi Devi\nAny other traditional right: Hunting rights', {'entities': [(23, 35, 'PARENT_NAME'), (65, 79, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Jagdalpur\nDistrict: Bilaspur\nScheduled Tribe: No', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (67, 75, 'DISTRICT'), (93, 95, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Kundapur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 35, 'PARENT_NAME'), (52, 60, 'GRAM_PANCHAYAT'), (93, 104, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Jagdalpur\nEvidence in support: Pending submission', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (78, 96, 'EVIDENCE')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Raipur\nPattas/leases/grants, if any: Pending', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 45, 'DISTRICT'), (76, 83, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of spouse: Sita Devi\nDistrict: Raipur\nPattas/leases/grants, if any: Not applicable', {'entities': [(16, 25, 'SPOUSE_NAME'), (36, 42, 'DISTRICT'), (73, 87, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of spouse: Pooja\nDistrict: Kurnool\nPattas/leases/grants, if any: Pending', {'entities': [(16, 21, 'SPOUSE_NAME'), (32, 39, 'DISTRICT'), (70, 77, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the spouse: Sita Devi\nTehsil/Taluka: Sihora\nScheduled Tribe: No', {'entities': [(20, 29, 'SPOUSE_NAME'), (45, 51, 'TEHSIL'), (69, 71, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Gudur\nDisputed lands if any: None', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 80, 'DISPUTED_LANDS')]}),
    ('Name of spouse: Mohan Lal\nDistrict: Bilaspur\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 25, 'SPOUSE_NAME'), (36, 44, 'DISTRICT'), (75, 87, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Rampur\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 53, 'VILLAGE'), (75, 103, 'EVIDENCE')]}),
    ('Name of the spouse: Sunita\nTehsil/Taluka: Bilaspur\nScheduled Tribe: No', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 50, 'TEHSIL'), (68, 70, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Neeraj Kumar\nVillage: Katni\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (74, 102, 'EVIDENCE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Rampur\nExtent of forest land occupied: 2 hectares', {'entities': [(23, 35, 'PARENT_NAME'), (52, 58, 'GRAM_PANCHAYAT'), (91, 101, 'FOREST_LAND_EXTENT')]}),
    ('Name of father/mother: Lakshmi Devi\nAny other traditional right: Hunting rights', {'entities': [(23, 35, 'PARENT_NAME'), (65, 79, 'OTHER_RIGHT')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Kundapur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 33, 'PARENT_NAME'), (50, 58, 'GRAM_PANCHAYAT'), (91, 102, 'FOREST_LAND_EXTENT')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Raipur\nPattas/leases/grants, if any: Pending', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 45, 'DISTRICT'), (76, 83, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of father/mother: Radha Bai\nGram Panchayat: Rampur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 32, 'PARENT_NAME'), (49, 55, 'GRAM_PANCHAYAT'), (88, 95, 'FOREST_LAND_EXTENT')]}),
    ('Name of spouse: Sunita\nDistrict: Sihora\nPattas/leases/grants, if any: Pending', {'entities': [(16, 22, 'SPOUSE_NAME'), (33, 39, 'DISTRICT'), (70, 77, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of father/mother: Suresh Singh\nAny other traditional right: Hunting rights', {'entities': [(23, 35, 'PARENT_NAME'), (65, 79, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Gudur\nEvidence in support: Pending submission', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 49, 'VILLAGE'), (71, 89, 'EVIDENCE')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Badwara\nEvidence in support: Certificate attached', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 54, 'VILLAGE'), (76, 96, 'EVIDENCE')]}),
    ('Name of the spouse: Mohan Lal\nTehsil/Taluka: Rampur\nScheduled Tribe: No', {'entities': [(20, 29, 'SPOUSE_NAME'), (45, 51, 'TEHSIL'), (69, 71, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Jagdalpur\nDisputed lands if any: Partial', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 54, 'VILLAGE'), (78, 85, 'DISPUTED_LANDS')]}),
    ('Name of father/mother: Suresh Singh\nAny other traditional right: Hunting rights', {'entities': [(23, 35, 'PARENT_NAME'), (65, 79, 'OTHER_RIGHT')]}),
    ('Name of the spouse: Rajesh\nTehsil/Taluka: Bilaspur\nScheduled Tribe: Yes', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 50, 'TEHSIL'), (68, 71, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Neeraj Kumar\nVillage: Katni\nDistrict: Raipur\nScheduled Tribe: No', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (63, 69, 'DISTRICT'), (87, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of the spouse: Mohan Lal\nTehsil/Taluka: Sihora\nScheduled Tribe: No', {'entities': [(20, 29, 'SPOUSE_NAME'), (45, 51, 'TEHSIL'), (69, 71, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Lakshmi Devi\nAny other traditional right: Hunting rights', {'entities': [(23, 35, 'PARENT_NAME'), (65, 79, 'OTHER_RIGHT')]}),
    ('Name of spouse: Sunita\nDistrict: Bilaspur\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 22, 'SPOUSE_NAME'), (33, 41, 'DISTRICT'), (72, 84, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Badwara\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 54, 'VILLAGE'), (78, 85, 'DISPUTED_LANDS')]}),
    ('Name of father/mother: Radha Bai\nAny other traditional right: Hunting rights', {'entities': [(23, 32, 'PARENT_NAME'), (62, 76, 'OTHER_RIGHT')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Rampur\nExtent of forest land occupied: 2 hectares', {'entities': [(23, 33, 'PARENT_NAME'), (50, 56, 'GRAM_PANCHAYAT'), (89, 99, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Jagdalpur\nEvidence in support: Pending submission', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (78, 96, 'EVIDENCE')]}),
    ('Name of the claimant(s): Arvind Yadav\nTehsil/Taluka: Sihora\nLand for in situ rehabilitation: Not applicable', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 59, 'TEHSIL'), (93, 107, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Anita Sharma\nTehsil/Taluka: Rampur\nLand for in situ rehabilitation: Required', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 59, 'TEHSIL'), (93, 101, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Neeraj Kumar\nVillage: Katni\nDisputed lands if any: Entire area', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 87, 'DISPUTED_LANDS')]}),
    ('Name of the spouse: Pooja\nTehsil/Taluka: Rampur\nScheduled Tribe: Yes', {'entities': [(20, 25, 'SPOUSE_NAME'), (41, 47, 'TEHSIL'), (65, 68, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Katni\nDistrict: Kurnool\nScheduled Tribe: Yes', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (63, 70, 'DISTRICT'), (88, 91, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Anita Sharma\nTehsil/Taluka: Bilaspur\nLand for in situ rehabilitation: Not applicable', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 61, 'TEHSIL'), (95, 109, 'REHAB_LAND')]}),
    ('Name of spouse: Sunita\nDistrict: Kurnool\nPattas/leases/grants, if any: Not applicable', {'entities': [(16, 22, 'SPOUSE_NAME'), (33, 40, 'DISTRICT'), (71, 85, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Katni\nDisputed lands if any: None', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 80, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Ramesh Kumar\nVillage: Badwara\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 54, 'VILLAGE'), (76, 104, 'EVIDENCE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Rajpur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 35, 'PARENT_NAME'), (52, 58, 'GRAM_PANCHAYAT'), (91, 98, 'FOREST_LAND_EXTENT')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Kurnool\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 46, 'DISTRICT'), (77, 89, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the spouse: Sunita\nTehsil/Taluka: Sihora\nScheduled Tribe: No', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 48, 'TEHSIL'), (66, 68, 'SCHEDULED_TRIBE')]}),
    ('Name of spouse: Mohan Lal\nDistrict: Sihora\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 25, 'SPOUSE_NAME'), (36, 42, 'DISTRICT'), (73, 85, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Rampur\nDisputed lands if any: Entire area', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 53, 'VILLAGE'), (77, 88, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nTehsil/Taluka: Katni\nLand for in situ rehabilitation: Under process', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 58, 'TEHSIL'), (92, 105, 'REHAB_LAND')]}),
    ('Name of father/mother: Radha Bai\nAny other traditional right: Hunting rights', {'entities': [(23, 32, 'PARENT_NAME'), (62, 76, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Gudur\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (74, 102, 'EVIDENCE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Kundapur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 35, 'PARENT_NAME'), (52, 60, 'GRAM_PANCHAYAT'), (93, 100, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Gudur\nDistrict: Bilaspur\nScheduled Tribe: No', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (63, 71, 'DISTRICT'), (89, 91, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Neeraj Kumar\nVillage: Gudur\nEvidence in support: Certificate attached', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (74, 94, 'EVIDENCE')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Gudur\nDistrict: Bilaspur\nScheduled Tribe: No', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 50, 'VILLAGE'), (61, 69, 'DISTRICT'), (87, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Katni\nDisputed lands if any: None', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 80, 'DISPUTED_LANDS')]}),
    ('Name of spouse: Sunita\nDistrict: Kurnool\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 22, 'SPOUSE_NAME'), (33, 40, 'DISTRICT'), (71, 83, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Gudur\nDistrict: Bilaspur\nScheduled Tribe: Yes', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 49, 'VILLAGE'), (60, 68, 'DISTRICT'), (86, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Radha Bai\nAny other traditional right: Fishing rights', {'entities': [(23, 32, 'PARENT_NAME'), (62, 76, 'OTHER_RIGHT')]}),
    ('Name of father/mother: Radha Bai\nGram Panchayat: Rampur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 32, 'PARENT_NAME'), (49, 55, 'GRAM_PANCHAYAT'), (88, 99, 'FOREST_LAND_EXTENT')]}),
    ('Name of the spouse: Pooja\nTehsil/Taluka: Rampur\nScheduled Tribe: Yes', {'entities': [(20, 25, 'SPOUSE_NAME'), (41, 47, 'TEHSIL'), (65, 68, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Ramesh Kumar\nTehsil/Taluka: Katni\nLand for in situ rehabilitation: Under process', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 58, 'TEHSIL'), (92, 105, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Badwara\nDistrict: Raipur\nScheduled Tribe: Yes', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 51, 'VILLAGE'), (62, 68, 'DISTRICT'), (86, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Neeraj Kumar\nTehsil/Taluka: Rampur\nLand for in situ rehabilitation: Not applicable', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 59, 'TEHSIL'), (93, 107, 'REHAB_LAND')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Rampur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 33, 'PARENT_NAME'), (50, 56, 'GRAM_PANCHAYAT'), (89, 100, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Tara Singh\nTehsil/Taluka: Bilaspur\nLand for in situ rehabilitation: Not applicable', {'entities': [(25, 35, 'CLAIMANT_NAME'), (51, 59, 'TEHSIL'), (93, 107, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Neeraj Kumar\nVillage: Rampur\nDisputed lands if any: None', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 53, 'VILLAGE'), (77, 81, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Jagdalpur\nEvidence in support: Pending submission', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 53, 'VILLAGE'), (75, 93, 'EVIDENCE')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Rampur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 33, 'PARENT_NAME'), (50, 56, 'GRAM_PANCHAYAT'), (89, 96, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Gudur\nEvidence in support: Authenticated copy available', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (74, 102, 'EVIDENCE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Kundapur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 35, 'PARENT_NAME'), (52, 60, 'GRAM_PANCHAYAT'), (93, 100, 'FOREST_LAND_EXTENT')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Rajpur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 33, 'PARENT_NAME'), (50, 56, 'GRAM_PANCHAYAT'), (89, 96, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Gudur\nDistrict: Bilaspur\nScheduled Tribe: Yes', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (63, 71, 'DISTRICT'), (89, 92, 'SCHEDULED_TRIBE')]}),
    ('Name of the spouse: Sunita\nTehsil/Taluka: Sihora\nScheduled Tribe: No', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 48, 'TEHSIL'), (66, 68, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Lakshmi Devi\nGram Panchayat: Kundapur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 35, 'PARENT_NAME'), (52, 60, 'GRAM_PANCHAYAT'), (93, 100, 'FOREST_LAND_EXTENT')]}),
    ('Name of father/mother: Suresh Singh\nAny other traditional right: Hunting rights', {'entities': [(23, 35, 'PARENT_NAME'), (65, 79, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Katni\nDisputed lands if any: Entire area', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 87, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Gudur\nDistrict: Bilaspur\nScheduled Tribe: No', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 49, 'VILLAGE'), (60, 68, 'DISTRICT'), (86, 88, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Rampur\nDisputed lands if any: Entire area', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 50, 'VILLAGE'), (74, 85, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Badwara\nDistrict: Kurnool\nScheduled Tribe: No', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 52, 'VILLAGE'), (63, 70, 'DISTRICT'), (88, 90, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Gudur\nDistrict: Raipur\nScheduled Tribe: No', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (63, 69, 'DISTRICT'), (87, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Kamla Devi\nAny other traditional right: Fishing rights', {'entities': [(23, 33, 'PARENT_NAME'), (63, 77, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Neeraj Kumar\nTehsil/Taluka: Rampur\nLand for in situ rehabilitation: Required', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 59, 'TEHSIL'), (93, 101, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Katni\nEvidence in support: Pending submission', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (74, 92, 'EVIDENCE')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Jagdalpur\nDistrict: Raipur\nScheduled Tribe: No', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 54, 'VILLAGE'), (65, 71, 'DISTRICT'), (89, 91, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Pankaj Kumar\nVillage: Katni\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 83, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Gudur\nDistrict: Bilaspur\nScheduled Tribe: No', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 50, 'VILLAGE'), (61, 69, 'DISTRICT'), (87, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Badwara\nDisputed lands if any: None', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 54, 'VILLAGE'), (78, 82, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Gudur\nDisputed lands if any: Partial', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 49, 'VILLAGE'), (73, 80, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Katni\nDisputed lands if any: Partial', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 50, 'VILLAGE'), (74, 81, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Tara Singh\nVillage: Badwara\nEvidence in support: Authenticated copy available', {'entities': [(25, 35, 'CLAIMANT_NAME'), (45, 52, 'VILLAGE'), (74, 102, 'EVIDENCE')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Badwara\nEvidence in support: Certificate attached', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 54, 'VILLAGE'), (76, 96, 'EVIDENCE')]}),
    ('Name of father/mother: Radha Bai\nGram Panchayat: Rajpur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 32, 'PARENT_NAME'), (49, 55, 'GRAM_PANCHAYAT'), (88, 99, 'FOREST_LAND_EXTENT')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Rampur\nDistrict: Kurnool\nScheduled Tribe: Yes', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 50, 'VILLAGE'), (61, 68, 'DISTRICT'), (86, 89, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Jagdalpur\nDisputed lands if any: Entire area', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 53, 'VILLAGE'), (77, 88, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nTehsil/Taluka: Katni\nLand for in situ rehabilitation: Not applicable', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 58, 'TEHSIL'), (92, 106, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Ramesh Kumar\nTehsil/Taluka: Bilaspur\nLand for in situ rehabilitation: Under process', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 61, 'TEHSIL'), (95, 108, 'REHAB_LAND')]}),
    ('Name of spouse: Rajesh\nDistrict: Kurnool\nPattas/leases/grants, if any: Pending', {'entities': [(16, 22, 'SPOUSE_NAME'), (33, 40, 'DISTRICT'), (71, 78, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the spouse: Mohan Lal\nTehsil/Taluka: Sihora\nScheduled Tribe: No', {'entities': [(20, 29, 'SPOUSE_NAME'), (45, 51, 'TEHSIL'), (69, 71, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Radha Bai\nGram Panchayat: Rampur\nExtent of forest land occupied: 5 square km', {'entities': [(23, 32, 'PARENT_NAME'), (49, 55, 'GRAM_PANCHAYAT'), (88, 99, 'FOREST_LAND_EXTENT')]}),
    ('Name of father/mother: Radha Bai\nAny other traditional right: Hunting rights', {'entities': [(23, 32, 'PARENT_NAME'), (62, 76, 'OTHER_RIGHT')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Rampur\nDisputed lands if any: Partial', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 50, 'VILLAGE'), (74, 81, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Sita Devi\nVillage: Katni\nDistrict: Sihora\nScheduled Tribe: No', {'entities': [(25, 34, 'CLAIMANT_NAME'), (44, 49, 'VILLAGE'), (60, 66, 'DISTRICT'), (84, 86, 'SCHEDULED_TRIBE')]}),
    ('Name of spouse: Pooja\nDistrict: Bilaspur\nPattas/leases/grants, if any: Not applicable', {'entities': [(16, 21, 'SPOUSE_NAME'), (32, 40, 'DISTRICT'), (71, 85, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nTehsil/Taluka: Bilaspur\nLand for in situ rehabilitation: Not applicable', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 61, 'TEHSIL'), (95, 109, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Badwara\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 54, 'VILLAGE'), (78, 85, 'DISPUTED_LANDS')]}),
    ('Name of the spouse: Sunita\nTehsil/Taluka: Sihora\nScheduled Tribe: Yes', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 48, 'TEHSIL'), (66, 69, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Suresh Singh\nGram Panchayat: Rajpur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 35, 'PARENT_NAME'), (52, 58, 'GRAM_PANCHAYAT'), (91, 98, 'FOREST_LAND_EXTENT')]}),
    ('Name of father/mother: Suresh Singh\nAny other traditional right: Grazing', {'entities': [(23, 35, 'PARENT_NAME'), (65, 72, 'OTHER_RIGHT')]}),
    ('Name of the spouse: Sunita\nTehsil/Taluka: Bilaspur\nScheduled Tribe: No', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 50, 'TEHSIL'), (68, 70, 'SCHEDULED_TRIBE')]}),
    ('Name of the spouse: Pooja\nTehsil/Taluka: Rampur\nScheduled Tribe: Yes', {'entities': [(20, 25, 'SPOUSE_NAME'), (41, 47, 'TEHSIL'), (65, 68, 'SCHEDULED_TRIBE')]}),
    ('Name of the spouse: Sita Devi\nTehsil/Taluka: Rampur\nScheduled Tribe: No', {'entities': [(20, 29, 'SPOUSE_NAME'), (45, 51, 'TEHSIL'), (69, 71, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Radha Bai\nAny other traditional right: Grazing', {'entities': [(23, 32, 'PARENT_NAME'), (62, 69, 'OTHER_RIGHT')]}),
    ('Name of spouse: Mohan Lal\nDistrict: Kurnool\nPattas/leases/grants, if any: Patta issued', {'entities': [(16, 25, 'SPOUSE_NAME'), (36, 43, 'DISTRICT'), (74, 86, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Arvind Yadav\nVillage: Katni\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 52, 'VILLAGE'), (76, 83, 'DISPUTED_LANDS')]}),
    ('Name of the spouse: Rajesh\nTehsil/Taluka: Sihora\nScheduled Tribe: Yes', {'entities': [(20, 26, 'SPOUSE_NAME'), (42, 48, 'TEHSIL'), (66, 69, 'SCHEDULED_TRIBE')]}),
    ('Name of the claimant(s): Anita Sharma\nVillage: Rampur\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 53, 'VILLAGE'), (77, 84, 'DISPUTED_LANDS')]}),
    ('Name of the claimant(s): Pankaj Kumar\nTehsil/Taluka: Bilaspur\nLand for in situ rehabilitation: Required', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 61, 'TEHSIL'), (95, 103, 'REHAB_LAND')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Raipur\nPattas/leases/grants, if any: Pending', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 45, 'DISTRICT'), (76, 83, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of the claimant(s): Arvind Yadav\nTehsil/Taluka: Bilaspur\nLand for in situ rehabilitation: Under process', {'entities': [(25, 37, 'CLAIMANT_NAME'), (53, 61, 'TEHSIL'), (95, 108, 'REHAB_LAND')]}),
    ('Name of the claimant(s): Ramesh Kumar\nVillage: Jagdalpur\nDisputed lands if any: Partial', {'entities': [(25, 37, 'CLAIMANT_NAME'), (47, 56, 'VILLAGE'), (80, 87, 'DISPUTED_LANDS')]}),
    ('Name of spouse: Radha Kumari\nDistrict: Bilaspur\nPattas/leases/grants, if any: Pending', {'entities': [(16, 28, 'SPOUSE_NAME'), (39, 47, 'DISTRICT'), (78, 85, 'PATTAS_LEASES_GRANTS')]}),
    ('Name of father/mother: Kamla Devi\nGram Panchayat: Rampur\nExtent of forest land occupied: 3 acres', {'entities': [(23, 33, 'PARENT_NAME'), (50, 56, 'GRAM_PANCHAYAT'), (89, 96, 'FOREST_LAND_EXTENT')]}),
    ('Name of the spouse: Mohan Lal\nTehsil/Taluka: Katni\nScheduled Tribe: No', {'entities': [(20, 29, 'SPOUSE_NAME'), (45, 50, 'TEHSIL'), (68, 70, 'SCHEDULED_TRIBE')]}),
    ('Name of father/mother: Kamla Devi\nAny other traditional right: Hunting rights', {'entities': [(23, 33, 'PARENT_NAME'), (63, 77, 'OTHER_RIGHT')]}),
]
